### ISSUE TITLE
Facebook login not working on demo

### ISSUE THREAD

**Issue by darkoverlordofdata** [ccoenraets/sociogram-angular-ionic#7]
I’ve tried the demo (http://coenraets.org/apps/sociogram/index.html#/app/login) on both my desktop and android phone, but it doesn’t work. I get this error:

Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App’s settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App’s domains.

**Comment by joshjhargreaves** [comment]
You'll need to clone the project and and initalise openFb with an appId and a callback url (like it says in the main _readme_.
![image](https://cloud.githubusercontent.com/assets/1807207/4265003/6e388148-3c3b-11e4-9e3b-8ed7af915f80.png)

You can make a facebook app at _developer.facebook.com_, and set valid callback urls in the advanced section. If serving locally with _ionic serve_, your callback URL will be something like _http://localhost:PORTNUMBER_.

You will probably also need to intialise openFB with a callback url, which with ionic serve will be _http://localhost:PORTNUMBER/oauthcallback.html_

This issue should be marked as closed.
